services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: always

  database:
    image: mongo:latest
    container_name: mongodb-adam
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: